#!/usr/bin/env python
# -*- coding: utf-8 -*-

# @copyright &copy; 2010 - 2018, Fraunhofer-Gesellschaft zur Foerderung der
#   angewandten Forschung e.V. All rights reserved.
#
# BSD 3-Clause License
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 1.  Redistributions of source code must retain the above copyright notice,
#     this list of conditions and the following disclaimer.
# 2.  Redistributions in binary form must reproduce the above copyright notice,
#     this list of conditions and the following disclaimer in the documentation
#     and/or other materials provided with the distribution.
# 3.  Neither the name of the copyright holder nor the names of its
#     contributors may be used to endorse or promote products derived from this
#     software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# We kindly request you to use one or more of the following phrases to refer to
# foxBMS in your hardware, software, documentation or advertising materials:
#
# &Prime;This product uses parts of foxBMS&reg;&Prime;
#
# &Prime;This product includes parts of foxBMS&reg;&Prime;
#
# &Prime;This product is derived from foxBMS&reg;&Prime;

"""WAF script for building "foxbms-module" library.
location of this wscript:
    /src/module/wscript
"""

import os


def build(bld):
    srcs = ' '.join([
           os.path.join('hwinfo', 'hwinfo.c'),
           os.path.join('interlock', 'interlock.c'),
           os.path.join('meas', 'meas.c'),
           os.path.join('ltc', 'ltc.c'),
           os.path.join('ltc', 'ltc_pec.c'),
           os.path.join('led', 'led.c'),

           os.path.join('..', '..', '..', bld.env.__bld_project, 'src', 'module', 'config', 'interlock_cfg.c'),
           os.path.join('..', '..', '..', bld.env.__bld_project, 'src', 'module', 'config', 'ltc_cfg.c'),
           os.path.join('..', '..', '..', bld.env.__bld_project, 'src', 'module', 'config', 'meas_cfg.c'),
           os.path.join('..', '..', '..', bld.env.__bld_project, 'src', 'module', 'config', 'nvram_cfg.c')])

    if bld.variant == 'primary':
        srcs += ' ' + ' '.join([
                os.path.join('cansignal', 'cansignal.c'),
                os.path.join('..', '..', '..', bld.env.__bld_project, 'src', 'module', 'config', 'cansignal_cfg.c')])
    elif bld.variant == 'secondary':
        srcs += ' ' + ' '.join([])

    includes = os.path.join(bld.bldnode.abspath()) + ' '
    includes += bld.env.__inc_FreeRTOS + ' '
    includes += bld.env.__inc_hal + ' '
    includes += ' '.join([
                '.',
                os.path.join('ltc'),

                os.path.join('..', 'driver', 'adc'),
                os.path.join('..', 'driver', 'dma'),
                os.path.join('..', 'driver', 'io'),
                os.path.join('..', 'driver', 'mcu'),
                os.path.join('..', 'driver', 'rcc'),
                os.path.join('..', 'driver', 'rtc'),
                os.path.join('..', 'driver', 'spi'),
                os.path.join('..', 'driver', 'uart'),

                os.path.join('..', 'engine', 'database'),

                os.path.join(bld.top_dir, bld.env.__sw_dir, bld.env.__bld_project, 'src', 'application', 'config'),

                os.path.join(bld.top_dir, bld.env.__sw_dir, bld.env.__bld_project, 'src', 'driver', 'config'),

                os.path.join(bld.top_dir, bld.env.__sw_dir, bld.env.__bld_project, 'src', 'engine', 'config'),
                os.path.join(bld.top_dir, bld.env.__sw_dir, bld.env.__bld_project, 'src', 'engine', 'diag'),
                os.path.join(bld.top_dir, bld.env.__sw_dir, bld.env.__bld_project, 'src', 'engine', 'sys'),

                os.path.join(bld.top_dir, bld.env.__sw_dir, bld.env.__bld_project, 'src', 'general', 'config'),
                os.path.join(bld.top_dir, bld.env.__sw_dir, bld.env.__bld_project, 'src', 'general', 'config', bld.env.CPU_MAJOR),
                os.path.join(bld.top_dir, bld.env.__sw_dir, bld.env.__bld_project, 'src', 'general', 'includes'),

                os.path.join(bld.top_dir, bld.env.__sw_dir, bld.env.__bld_project, 'src', 'module', 'config'),
                os.path.join(bld.top_dir, bld.env.__sw_dir, bld.env.__bld_project, 'src', 'module', 'nvram'),

                os.path.join(bld.top_dir, bld.env.__sw_dir, bld.env.__bld_project, 'src', 'os')])

    includes += ' '

    if bld.variant == 'primary':
        includes += ' '.join([
                    '.',
                    os.path.join('cansignal'),

                    os.path.join('..', 'driver', 'can'),

                    os.path.join(bld.top_dir, bld.env.__sw_dir, bld.env.__bld_project, 'src', 'application', 'bal'),
                    os.path.join(bld.top_dir, bld.env.__sw_dir, bld.env.__bld_project, 'src', 'application', 'sox')])
    elif bld.variant == 'secondary':
        includes += ' '.join([
                    '.'])

    bld.stlib(target='foxbms-common-module',
              source=srcs,
              includes=includes)
