#!/usr/bin/env python
# -*- coding: utf-8 -*-

# @copyright &copy; 2010 - 2018, Fraunhofer-Gesellschaft zur Foerderung der
#   angewandten Forschung e.V. All rights reserved.
#
# BSD 3-Clause License
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 1.  Redistributions of source code must retain the above copyright notice,
#     this list of conditions and the following disclaimer.
# 2.  Redistributions in binary form must reproduce the above copyright notice,
#     this list of conditions and the following disclaimer in the documentation
#     and/or other materials provided with the distribution.
# 3.  Neither the name of the copyright holder nor the names of its
#     contributors may be used to endorse or promote products derived from this
#     software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# We kindly request you to use one or more of the following phrases to refer to
# foxBMS in your hardware, software, documentation or advertising materials:
#
# &Prime;This product uses parts of foxBMS&reg;&Prime;
#
# &Prime;This product includes parts of foxBMS&reg;&Prime;
#
# &Prime;This product is derived from foxBMS&reg;&Prime;

"""WAF script for building "foxbms-engine" library.
location of this wscript:
    /src/engine/wscript

library output:
    /build/src/engine/libfoxbms-engine.a

"""

import os


def build(bld):
    srcs = ' '.join([
           os.path.join('config', 'diag_cfg.c'),
           os.path.join('config', 'enginetask_cfg.c'),
           os.path.join('config', 'sys_cfg.c'),
           os.path.join('diag', 'diag.c'),
           os.path.join('task', 'enginetask.c'),
           os.path.join('sys', 'sys.c')])

    includes = os.path.join(bld.bldnode.abspath()) + ' '
    includes += bld.env.__inc_FreeRTOS + ' ' + bld.env.__inc_hal
    includes += ' '.join([
                '.',

                os.path.join('config'),
                os.path.join('diag'),
                os.path.join('sys'),
                os.path.join('task'),

                os.path.join('..', 'application', 'bal'),
                os.path.join('..', 'application', 'bms'),
                os.path.join('..', 'application', 'com'),
                os.path.join('..', 'application', 'config'),

                os.path.join('..', 'driver', 'adc'),
                os.path.join('..', 'driver', 'config'),

                os.path.join('..', 'general', 'config'),
                os.path.join('..', 'general', 'config', bld.env.CPU_MAJOR),
                os.path.join('..', 'general', 'includes'),

                os.path.join('..', 'module', 'config'),

                os.path.join('..', 'os'),

                os.path.join(bld.top_dir, bld.env.__sw_dir, bld.env.__bld_common, 'src', 'driver', 'adc'),
                os.path.join(bld.top_dir, bld.env.__sw_dir, bld.env.__bld_common, 'src', 'driver', 'io'),
                os.path.join(bld.top_dir, bld.env.__sw_dir, bld.env.__bld_common, 'src', 'driver', 'mcu'),
                os.path.join(bld.top_dir, bld.env.__sw_dir, bld.env.__bld_common, 'src', 'driver', 'rtc'),
                os.path.join(bld.top_dir, bld.env.__sw_dir, bld.env.__bld_common, 'src', 'driver', 'spi'),
                os.path.join(bld.top_dir, bld.env.__sw_dir, bld.env.__bld_common, 'src', 'driver', 'vic'),
                os.path.join(bld.top_dir, bld.env.__sw_dir, bld.env.__bld_common, 'src', 'driver', 'watchdog'),

                os.path.join(bld.top_dir, bld.env.__sw_dir, bld.env.__bld_common, 'src', 'engine', 'database'),

                os.path.join(bld.top_dir, bld.env.__sw_dir, bld.env.__bld_common, 'src', 'module', 'interlock'),
                os.path.join(bld.top_dir, bld.env.__sw_dir, bld.env.__bld_common, 'src', 'module', 'ltc'),
                os.path.join(bld.top_dir, bld.env.__sw_dir, bld.env.__bld_common, 'src', 'module', 'meas'),

                os.path.join(bld.top_dir, bld.env.__sw_dir, bld.env.__bld_common, 'src', 'util')])

    bld.stlib(target='foxbms-engine',
              source=srcs,
              includes=includes)
